# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dae667415989e7b4b24be355c5d9a544d88f4aa7ef58204914bae25aebec749873fe2f30a4519ca46cb20fab34c9a8e63ed30cd87b9611051e3affb402acac7a

test:
  secret_key_base: 2897fa7316ca154a9d6a4a4db21b4f7385adc0383d1edf4b302fe77994471a778ba3b7213f9acbc9c370252661dd5e695d1a4944fd958b46c6fabef9500970c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
